name: Build and Publish Docker Image

on:
  push:
    tags:
      - 'v*'
      - '[0-9]+.*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable={{is_default_branch}}
          labels: |
            org.opencontainers.image.description=MehPress
            org.opencontainers.image.vendor=MoonTechs
            org.opencontainers.image.version={{version}}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Build and push multi-platform image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=build-multiplatform
          cache-to: type=gha,scope=build-multiplatform,mode=max

      - name: Output image details
        run: |
          echo "Successfully built and pushed multi-platform image:"
          echo "Repository: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
          echo "Tags:"
          echo "${{ steps.meta.outputs.tags }}" | sed 's/^/  - /'
          echo "Platforms: linux/amd64, linux/arm64"
